# This is a basic workflow to help you get started with Actions mouredev

name: stats

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
      - uses: actions/checkout@v4

      # configurar py
      - name: setup python
      - uses: actions/setup-python@v5
        with:
           python-version: "3.11"

      # - run: python myscript
      - name: Run  script
         run:  python /Roadmap/stats.py
      
      - name: commit and push changes
        uses: stefanzweifel/git-auto-commit-action
        with:
           commit_message:  update stats
           commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
           commit_user_email: my-github-actions-bot@example.org
            commit_author: Author <actions@github.com> # defaults to "username <username@users.noreply.github.com>"



        
